# Generated by Django 4.2 on 2023-08-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_symbol_qty_decs_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klines',
            old_name='creado',
            new_name='datetime',
        ),
        migrations.AlterField(
            model_name='symbol',
            name='symbol',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='klines',
            unique_together={('symbol', 'datetime')},
        ),
    ]
