# Generated by Django 4.2 on 2023-08-20 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_rename_creado_klines_datetime_alter_symbol_symbol_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Klines',
            new_name='Kline',
        ),
    ]
