# Generated by Django 4.2 on 2023-08-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_rename_klines_kline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kline',
            name='datetime',
            field=models.DateTimeField(db_index=True),
        ),
    ]
