# Generated by Django 4.2 on 2023-08-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_kline_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='activo',
            field=models.IntegerField(default=0),
        ),
    ]
