# Generated by Django 4.2 on 2023-08-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_symbol_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='flag',
            field=models.IntegerField(default=0),
        ),
    ]
