# Generated by Django 4.2 on 2023-10-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_order_flag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kline',
            options={'verbose_name_plural': 'Velas'},
        ),
        migrations.AlterModelOptions(
            name='symbol',
            options={'verbose_name': 'Par', 'verbose_name_plural': 'Pares'},
        ),
        migrations.AddField(
            model_name='bot',
            name='max_drowdown',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estrategia',
            name='max_drowdown',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='symbol',
            name='symbol',
            field=models.CharField(max_length=16, unique=True, verbose_name='Nombre del par'),
        ),
    ]
