# Generated by Django 4.2 on 2023-10-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_kline_options_alter_symbol_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estrategia',
            name='descripcion',
            field=models.TextField(default='A'),
            preserve_default=False,
        ),
    ]
