# Generated by Django 4.2 on 2023-10-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_estrategia_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estrategia',
            name='interval_id',
            field=models.CharField(default='1d01', max_length=8),
            preserve_default=False,
        ),
    ]
