# Generated by Django 4.2 on 2023-10-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_estrategia_interval_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='stop_loss',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=6),
            preserve_default=False,
        ),
    ]
