# Generated by Django 4.2 on 2023-10-04 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_bot_stop_loss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='interval_id',
        ),
    ]
