# Generated by Django 4.2 on 2023-10-05 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_remove_bot_parametros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='max_drowdown',
            new_name='max_drawdown',
        ),
        migrations.RenameField(
            model_name='estrategia',
            old_name='max_drowdown',
            new_name='max_drawdown',
        ),
    ]
