# Generated by Django 4.2 on 2023-10-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_alter_estrategia_max_drawdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='max_drawdown',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bot',
            name='quote_qty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bot',
            name='stop_loss',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.FloatField(),
        ),
    ]
