# Generated by Django 4.2.6 on 2023-10-17 03:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_order_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='finalizado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('log_id', models.IntegerField(db_index=True, default=0)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bot')),
            ],
        ),
    ]
