# Generated by Django 4.2.6 on 2023-10-22 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0019_bot_finalizado_botlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='symbol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bot.symbol'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bot',
            name='estrategia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.estrategia'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='botlog',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.bot'),
        ),
        migrations.AlterField(
            model_name='kline',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.symbol'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.bot'),
        ),
    ]
