# Generated by Django 4.2.6 on 2023-10-22 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0020_order_symbol_alter_bot_estrategia_alter_bot_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='base_asset',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quote_asset',
        ),
        migrations.AlterField(
            model_name='bot',
            name='estrategia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.estrategia'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='botlog',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bot'),
        ),
        migrations.AlterField(
            model_name='kline',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.symbol'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bot'),
        ),
        migrations.AlterField(
            model_name='order',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.symbol'),
        ),
    ]
