# Generated by Django 4.2.6 on 2023-10-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_remove_order_base_asset_remove_order_quote_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kline',
            name='close',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kline',
            name='high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kline',
            name='low',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kline',
            name='open',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kline',
            name='volume',
            field=models.FloatField(),
        ),
    ]
