# Generated by Django 4.2.6 on 2023-10-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_alter_kline_close_alter_kline_high_alter_kline_low_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botlog',
            name='texto',
            field=models.TextField(blank=True, default=''),
        ),
    ]
