# Generated by Django 4.2.6 on 2023-10-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_botlog_texto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botlog',
            old_name='log_id',
            new_name='log_type_id',
        ),
    ]
