# Generated by Django 4.2.6 on 2023-11-03 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0024_rename_log_id_botlog_log_type_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.SlugField()),
                ('parametros', models.TextField()),
                ('interval_id', models.CharField(max_length=8)),
                ('estado', models.IntegerField(default=0)),
                ('completo', models.FloatField(default=0)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
