# Generated by Django 4.2.6 on 2023-11-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0025_backtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='scoring',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='backtest',
            name='scoring_str',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
