version: "3"

services:
  db_postgres:
    image: postgres:11.5
    volumes:
      - ./db_postgres:/var/lib/postgresql/data
  
  django_app:
    restart: always
    build: .
    volumes:
      - ./static:/app/static
      - ./ie/static:/app/ie/static
      - .:/app
    depends_on:
      - db_postgres
    
  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./static:/app/static
    depends_on:
      - django_app
