# Generated by Django 4.2 on 2023-08-19 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 13, 58, 54, 715618, tzinfo=datetime.timezone.utc)),
        ),
    ]
