# Generated by Django 4.2 on 2023-08-20 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_userprofile_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 15, 45, 33, 338427, tzinfo=datetime.timezone.utc)),
        ),
    ]
