# Generated by Django 4.2 on 2023-08-21 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_userprofile_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 15, 17, 36, 761141, tzinfo=datetime.timezone.utc)),
        ),
    ]
