# Generated by Django 4.2 on 2023-10-04 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_userprofile_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 14, 33, 32, 906144, tzinfo=datetime.timezone.utc)),
        ),
    ]
