# Generated by Django 4.2 on 2023-10-04 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_userprofile_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 15, 26, 25, 31119, tzinfo=datetime.timezone.utc)),
        ),
    ]
