# Generated by Django 4.2 on 2023-10-04 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_userprofile_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 23, 6, 38, 546228, tzinfo=datetime.timezone.utc)),
        ),
    ]
