# Generated by Django 4.2 on 2023-10-06 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_userprofile_key_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='config',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 14, 11, 33, 885019, tzinfo=datetime.timezone.utc)),
        ),
    ]
