# Generated by Django 4.2 on 2023-10-09 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_userprofile_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 15, 21, 45, 778964, tzinfo=datetime.timezone.utc)),
        ),
    ]
