# Generated by Django 4.2.6 on 2023-10-17 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_userprofile_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 19, 3, 0, 4, 513659, tzinfo=datetime.timezone.utc)),
        ),
    ]
