# Generated by Django 4.2.6 on 2023-10-22 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_userprofile_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 13, 41, 54, 262120, tzinfo=datetime.timezone.utc)),
        ),
    ]
