# Generated by Django 4.2.6 on 2023-10-28 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_userprofile_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 12, 23, 36, 791022, tzinfo=datetime.timezone.utc)),
        ),
    ]
