# Generated by Django 4.2.6 on 2023-10-28 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_userprofile_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 12, 26, 19, 555155, tzinfo=datetime.timezone.utc)),
        ),
    ]
