# Generated by Django 4.2.6 on 2023-11-03 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_userprofile_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 5, 11, 48, 5, 881933, tzinfo=datetime.timezone.utc)),
        ),
    ]
