# Generated by Django 4.2.6 on 2023-11-12 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_alter_userprofile_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 14, 21, 34, 38, 112034, tzinfo=datetime.timezone.utc)),
        ),
    ]
