# Generated by Django 4.1.10 on 2023-08-10 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 15, 26, 38, 265975, tzinfo=datetime.timezone.utc)),
        ),
    ]
